# Generated by Django 4.2.23 on 2025-08-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('legal_address', models.TextField()),
                ('physical_address', models.TextField()),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='clinics_cli_name_b61e6f_idx')],
            },
        ),
    ]
