# Generated by Django 4.2.23 on 2025-08-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinic',
            options={'ordering': ['name'], 'verbose_name': 'Клиника', 'verbose_name_plural': 'Клиники'},
        ),
        migrations.AlterField(
            model_name='clinic',
            name='legal_address',
            field=models.TextField(verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='physical_address',
            field=models.TextField(verbose_name='Физический адрес'),
        ),
    ]
