# Generated by Django 4.2.23 on 2025-08-10 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('end_time', models.DateTimeField(verbose_name='Время окончания')),
                ('status', models.CharField(choices=[('CONFIRMED', 'Подтверждена'), ('PENDING', 'Ожидает'), ('STARTED', 'Начата'), ('COMPLETED', 'Завершена'), ('PAID', 'Оплачена')], default='PENDING', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinics.clinic', verbose_name='Клиника')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_consultations', to=settings.AUTH_USER_MODEL, verbose_name='Врач')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_consultations', to=settings.AUTH_USER_MODEL, verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Консультация',
                'verbose_name_plural': 'Консультации',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='consultatio_status_787364_idx'), models.Index(fields=['start_time', 'end_time'], name='consultatio_start_t_d93a4f_idx'), models.Index(fields=['doctor'], name='consultatio_doctor__6ce364_idx'), models.Index(fields=['patient'], name='consultatio_patient_a5284f_idx'), models.Index(fields=['clinic'], name='consultatio_clinic__004b40_idx')],
            },
        ),
    ]
